#!/bin/bash

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

HELP_FILE=$SOURCE_DIR/../help.txt
BOOKMARKS_FILE=$SOURCE_DIR/bookmarks
MARK_HIST_FILE=$SOURCE_DIR/.mark_history

OPT_LIST_RECENT="-ls"
OPT_LIST_ALL="-lsa"
OPT_HELP="--help"

DeleteDuplicates_KeepLastOccurance(){
	COLUMN_TO_SORT=$(($1+1)) # add 1 to account for temp line number
	FILE=$2
	nl $2 | tac | sort -u -k "$COLUMN_TO_SORT,$COLUMN_TO_SORT" | sort -n | cut -f1 --complement
}

if [ $1 == $OPT_HELP ];
then
	cat $HELP_FILE

elif [ $1 == $OPT_LIST_RECENT ];
then
	NUM_LINES_TO_SHOW="${2:-10}"
	DeleteDuplicates_KeepLastOccurance 1 $MARK_HIST_FILE | tac | head -$NUM_LINES_TO_SHOW

elif [ $1 == $OPT_LIST_ALL ];
then
	cat $SOURCE_DIR/bookmarks

elif [[ "$1" == [a-z] ]]; 
then
	MARK_NAME=$1
	sed -i "s|^$MARK_NAME .*|$MARK_NAME $(pwd)|g" $BOOKMARKS_FILE
	echo $MARK_NAME $(pwd) >> $MARK_HIST_FILE
else
	>&2 echo "Invalid input"
	cat $HELP_FILE
	exit 1
fi

exit 0

